export const autoCompleteData = [
    "Toyota 1",
    "Toyota 2",
    "Toyota 3",
    "Toyota 4",
    "Toyota 5",
    "Toyota 6",
    "Toyota 7",
    "BMW 1",
    "BMW 2",
    "BMW 3",
    "BMW 4",
    "BMW 5",
    "BMW 6",
    "Ford 1",
    "Ford 2",
    "Ford 3",
    "Ford 4",
    "Ford 5",
    "Ford 6",
  ];